### ISSUE TITLE
gradle error reported on launch of intelliJ

### ISSUE THREAD

**Issue by spacemase** [gradle-archive/gradle-intellij-gui#10]
org/jetbrains/plugins/gradle/util/GradleLibraryManager: org/jetbrains/plugins/gradle/util/GradleLibraryManager
java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/util/GradleLibraryManager
    at org.gradle.ideaplugin.util.GradleUtils.getGradleLibraryManager(GradleUtils.java:64)
    at org.gradle.ideaplugin.util.GradleUtils.getGradleSDKDirectory(GradleUtils.java:59)
    at org.gradle.ideaplugin.ui.GradlePanelWrapper.reset(GradlePanelWrapper.java:99)
    at org.gradle.ideaplugin.ui.GradlePanelWrapper.initialize(GradlePanelWrapper.java:88)
    at org.gradle.ideaplugin.ui.MainGradleComponent.initComponent(MainGradleComponent.java:83)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponent(ComponentManagerImpl.java:217)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.access$1300(ComponentManagerImpl.java:55)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:587)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:630)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:242)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:229)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:127)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:346)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:309)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:278)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.access$300(ProjectManagerImpl.java:82)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$9.compute(ProjectManagerImpl.java:558)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$9.compute(ProjectManagerImpl.java:554)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$4.run(ProgressManagerImpl.java:269)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:495)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:304)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:185)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:175)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:681)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.gradle.util.GradleLibraryManager PluginClassLoader[Gradle GUI, 1.7]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 37 more

**Comment by Mart-Bogdan** [comment]
I have exactly the same error!

**Comment by dimka108** [comment]
The same error has been caught with intellij Idea 13.

**Comment by mortenholmgaard** [comment]
Same here
