### ISSUE TITLE
Error with loading gradle library is not helpful

### ISSUE THREAD

**Issue by LightGuard** [gradle-archive/gradle-intellij-gui#3]
Looks like I have a problem with my gradle install, but the exception in the details doesn't help me any:

<code>
Failed to load the gradle library (3).
Installation has multiple gradle jars. Cannot determine which one to use. Found files: [Ljava.io.File;@25703b9b
java.lang.RuntimeException: Installation has multiple gradle jars. Cannot determine which one to use. Found files: [Ljava.io.File;@25703b9b
    at org.gradle.openapi.external.ExternalUtility.getGradleJar(ExternalUtility.java:112)
    at org.gradle.openapi.external.ExternalUtility.getGradleClassloader(ExternalUtility.java:46)
    at org.gradle.openapi.external.ui.UIFactory.createDualPaneUI(UIFactory.java:132)
    at org.gradle.ideaplugin.ui.GradlePanelWrapper.loadUIFromGradle(GradlePanelWrapper.java:199)
    at org.gradle.ideaplugin.ui.GradlePanelWrapper.access$000(GradlePanelWrapper.java:67)
    at org.gradle.ideaplugin.ui.GradlePanelWrapper$1.run(GradlePanelWrapper.java:157)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:621)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:511)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:372)
    at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:678)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:168)
    at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:502)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:252)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:247)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:238)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectWithProgress(ProjectManagerImpl.java:450)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectWithProgress(ProjectManagerImpl.java:437)
    at com.intellij.openapi.project.impl.IdeaProjectManagerImpl.convertAndLoadProject(IdeaProjectManagerImpl.java:64)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:418)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:406)
    at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:165)
    at com.intellij.ide.RecentProjectsManager.doOpenProject(RecentProjectsManager.java:48)
    at com.intellij.ide.RecentProjectsManagerBase$ReopenProjectAction.actionPerformed(RecentProjectsManagerBase.java:225)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:478)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:621)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:511)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:372)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

/Users/jporter/java_libraries/gradle-0.9
</code>

We need to know which files it found, not the object instance

**Comment by alcmike** [comment]
Agreed, the comment needs to tell you the file. I'll get on that. A work-around is if you look into the lib directory of the gradle installation you're pointing to, you'll find multiple gradle\* jar files (gradle-core-xxxx.jar, gradle-launcher-xxxx.jar). One or more of those is duplicated, differing only by the version number at the end. Delete one of each duplicated file. Note however, the version numbers need to match among the grade-\* files you don't delete.
If you're pointing to a version of gradle you've built, try doing a clean then build again. If you're using a released version of gradle, contact gradle on the mailing lists as it shouldn't have duplicates.

Mike

**Comment by LightGuard** [comment]
I'm using the latest HEAD from git, still no workie after a gradlew clean install.
