### ISSUE TITLE
Throwing Exception on IDEA startup

### ISSUE THREAD

**Issue by eugenegligalov** [gradle-archive/gradle-intellij-gui#5]
org/jetbrains/plugins/groovy/gradle/GradleSettings: org/jetbrains/plugins/groovy/gradle/GradleSettings
java.lang.NoClassDefFoundError: org/jetbrains/plugins/groovy/gradle/GradleSettings
    at org.gradle.ideaplugin.ui.GradlePanelWrapper.reset(GradlePanelWrapper.java:101)
    at org.gradle.ideaplugin.ui.GradlePanelWrapper.initialize(GradlePanelWrapper.java:88)
    at org.gradle.ideaplugin.ui.MainGradleComponent.initComponent(MainGradleComponent.java:83)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.b(ComponentManagerImpl.java:212)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.access$1100(ComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:623)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:561)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:259)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:228)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:124)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:105)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:330)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:84)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:277)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:280)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.b(ProjectManagerImpl.java:313)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.access$400(ProjectManagerImpl.java:80)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$9.compute(ProjectManagerImpl.java:505)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$9.compute(ProjectManagerImpl.java:502)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:244)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:457)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$5.run(ProgressManagerImpl.java:276)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:169)
    at com.intellij.openapi.application.impl.ApplicationImpl$9$1.run(ApplicationImpl.java:634)
    at com.intellij.openapi.application.impl.ApplicationImpl$7.run(ApplicationImpl.java:429)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:138)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.groovy.gradle.GradleSettings PluginClassLoader[Gradle GUI, 1.4]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    ... 36 more

**Comment by alcmike** [comment]
What's the version of Idea and the plugin?
If you're on Idea 10, make sure you update the Gradle plugin.

**Comment by eugenegligalov** [comment]
I guess I found the problem I'm using Idea 11 EAP version plugin being migrated from old version and it doesn't exist for new one

**Comment by eugenegligalov** [comment]
Thanks :)

**Comment by alcmike** [comment]
I'll look into getting that working. IntelliJ seems to change things each release.

**Comment by alcmike** [comment]
This has been fixed. I've uploaded a new version (1.6) to IntelliJ's site. This version is only compatible with Idea 11 (and not 10). It sometimes takes awhile to show up in Idea (due to moderation). Note: I actually fixed this in the plugin version 1.5, but IntelliJ had just released an update that broke it.
