### ISSUE TITLE
NoClassDefFoundError on "Reload Gradle UI" click

### ISSUE THREAD

**Issue by sbszcz** [gradle-archive/gradle-intellij-gui#9]
Hello,

i am using IntelliJ Idea v126.330 and configured the gradle location in the settings menu. 

Clicking the "Reload Gradle UI" button throws the following exception:

NoClassDefFoundError: Error during dispatching of java.awt.event.MouseEvent[MOUSE_RELEASED,(226,308),absolute(218,300),button=1,modifiers=Button1,clickCount=1] on frame0: org/jetbrains/plugins/gradle/util/GradleLibraryManager

Plugin version is 1.7

**Comment by szpak** [comment]
The same exeception class, but with a different message in Idea 12.1 EAP (128.18) on an IDE start up.

```
org/jetbrains/plugins/gradle/util/GradleLibraryManager: org/jetbrains/plugins/gradle/util/GradleLibraryManager
java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/util/GradleLibraryManager
    at org.gradle.ideaplugin.util.GradleUtils.getGradleLibraryManager(GradleUtils.java:64)
    at org.gradle.ideaplugin.util.GradleUtils.getGradleSDKDirectory(GradleUtils.java:59)
    at org.gradle.ideaplugin.ui.GradlePanelWrapper.reset(GradlePanelWrapper.java:99)
    at org.gradle.ideaplugin.ui.GradlePanelWrapper.initialize(GradlePanelWrapper.java:88)
    at org.gradle.ideaplugin.ui.MainGradleComponent.initComponent(MainGradleComponent.java:83)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponent(ComponentManagerImpl.java:217)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.access$1300(ComponentManagerImpl.java:55)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:585)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:628)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:242)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:229)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:127)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:346)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:307)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:282)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.access$400(ProjectManagerImpl.java:82)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$10.compute(ProjectManagerImpl.java:562)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$10.compute(ProjectManagerImpl.java:558)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$4.run(ProgressManagerImpl.java:269)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:495)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:304)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:185)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:175)
(...)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.gradle.util.GradleLibraryManager PluginClassLoader[Gradle GUI, 1.7]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 37 more

```

**Comment by waynerasmuss** [comment]
This is still happening on the new version of idea released today.

IDEa 12.1 JDK 1.7 same stack trace as above

**Comment by swavkulinski** [comment]
Same on 12.1 IC JDK 1.6

**Comment by ctapobep** [comment]
2 months without resolution. Plugin is not working at all.

**Comment by barrybecker4** [comment]
I get the same error.

**Comment by danielesegato** [comment]
Same here

Android Studio

**Comment by kaamoss** [comment]
I'm also affected by this!

**Comment by hubertsa** [comment]
Same here, IDEA 12.1.4. Still no solution ?

**Comment by IgorGanapolsky** [comment]
Yup, same issue!  Android Studio 0.2.11

**Comment by nelwa** [comment]
Same issue here...please help.

**Comment by waynerasmuss** [comment]
To work around this I just created an external tool in Idea to launch the Gradle gui. It's just about as good. I created external tools to do a lot of things actually. Build All etc. It would be nice to have the plugin fixed, but the external tools approach gives just about the same functionality

**Comment by laminko** [comment]
same issue, too.

**Comment by mlgiter** [comment]
The very same story. Gradle GUI plugin crashes at ide startup

**Comment by hubertsa** [comment]
I am out of the office until 21/04/2015.

Note: This is an automated response to your message  "Re:
[gradle-intellij-gui] NoClassDefFoundError on "Reload Gradle UI" click
(#9)" sent on 17/04/2015 23:59:02.

This is the only notification you will receive while this person is away.
